apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: assisted-events-scrape-uzau
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-events-scrape/assisted-events-scrape-uzau@sha256:9b2d00bc4e9f094d28bfa305b17cd6c3d6a9dd610fb85e8c148cffcee0bed934
        name: container-image
        resources: {}
status: {}
